on:
  pull_request:

env:
  FILE_PROJECT_ROOT_ENV: ${{ secrets.FILE_PROJECT_ROOT_ENV }}
  FILE_IOS_GOOGLE_SERVICE_INFO_PLIST: ${{ secrets.FILE_IOS_GOOGLE_SERVICE_INFO_PLIST }}
  FILE_IOS_AMPLIFY_CONFIGURATION_JSON: ${{ secrets.FILE_IOS_AMPLIFY_CONFIGURATION_JSON }}
  FILE_IOS_AWS_CONFIGURATION_JSON: ${{ secrets.FILE_IOS_AWS_CONFIGURATION_JSON }}
  FILE_USER_ROOT_NETRC: ${{ secrets.FILE_USER_ROOT_NETRC }}
  ENV_FILE_NATIVE_CLIENT_URL: ${{ secrets.ENV_FILE_NATIVE_CLIENT_URL }}
  ENV_FILE_NATIVE_CLIENT_GRAPHQL_URL: ${{ secrets.ENV_FILE_NATIVE_CLIENT_GRAPHQL_URL }}
  ENV_FILE_NATIVE_CLIENT_GRAPHQL_API_KEY: ${{ secrets.ENV_FILE_NATIVE_CLIENT_GRAPHQL_API_KEY }}
  ENV_FILE_MAP_ACCESS_TOKEN: ${{ secrets.ENV_FILE_MAP_ACCESS_TOKEN }}
  ENV_FILE_SENTRY_DSN: ${{ secrets.ENV_FILE_SENTRY_DSN }}
  ENV_FILE_MAP_BOX_STYLE_URL_ANY: ${{ secrets.ENV_FILE_MAP_BOX_STYLE_URL_ANY }}
  ENV_FILE_MAP_BOX_STYLE_URL_DARK: ${{ secrets.ENV_FILE_MAP_BOX_STYLE_URL_DARK }}
  ENV_FILE_AMPLITUDE_KEY: ${{ secrets.ENV_FILE_AMPLITUDE_KEY }}
  ENV_FILE_MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.ENV_FILE_MAPBOX_DOWNLOADS_TOKEN }}

jobs:
  ios-unit-tests:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master

      - name: Create env file
        run: .github/workflows/scripts/create-env-file.sh

      - name: Create netrc file
        run: |
          echo $FILE_USER_ROOT_NETRC >> ~/.netrc
          chmod -R 0600 ~/.netrc

      - name: Create GoogleServiceInfo.plist file
        run: echo $FILE_IOS_GOOGLE_SERVICE_INFO_PLIST >> ./ios/GoogleService-Info.plist

      - name: Create amplifyconfiguration.json file
        run: echo $FILE_IOS_AMPLIFY_CONFIGURATION_JSON >> ./ios/amplifyconfiguration.json

      - name: Create awsconfiguration.json file
        run: echo $FILE_IOS_AWS_CONFIGURATION_JSON >> ./ios/awsconfiguration.json

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.5'
          bundler-cache: true

      - name: Install Bundle Dependencies
        run: bundle install

      - name: Install Yarn Dependencies
        run: yarn install

      - uses: actions/cache@v3
        with:
          path: ./ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Pod Dependencies
        run: cd ios && bundle exec pod install

      - uses: actions/cache/save@v3
        id: cache
        with:
          path: ./ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}

      - name: Fastlane tests
        run: bundle exec fastlane tests